const ActionTypes = {
    CREATE_CUSTOMER_SUCCESS: 'CREATE_CUSTOMER_SUCCESS',
    CREATE_CUSTOMER_PROGRESS: 'CREATE_CUSTOMER_PROGRESS',
    CREATE_CUSTOMER_FAILED: 'CREATE_CUSTOMER_FAILED',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_PROGRESS: 'GET_USER_PROGRESS',
    GET_USER_FAILED: 'GET_USER_FAILED'
};
export default ActionTypes;