const ActionTypes = {
    CREATE_CUSTOMER_SUCCESS: 'CREATE_CUSTOMER_SUCCESS',
    CREATE_CUSTOMER_PROGRESS: 'CREATE_CUSTOMER_PROGRESS',
    CREATE_CUSTOMER_FAILED: 'CREATE_CUSTOMER_FAILED'
};
export default ActionTypes;